# Generated by Django 5.1.6 on 2025-02-08 15:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("address", models.CharField(max_length=250)),
                ("age", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="patients/photos/"
                    ),
                ),
                (
                    "first_visit_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("last_visit_date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment", models.CharField(max_length=50)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patient_medication.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("disease", models.CharField(max_length=255)),
                ("medical_treatment", models.TextField()),
                (
                    "treatment_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="patient_medication.patient",
                    ),
                ),
            ],
        ),
    ]
